# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ver2_learn.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 0, 706, 191))
        self.widget.setObjectName("widget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.spray = QtWidgets.QLabel(self.widget)
        self.spray.setObjectName("spray")
        self.horizontalLayout_4.addWidget(self.spray)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.s_3_up = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s_3_up.sizePolicy().hasHeightForWidth())
        self.s_3_up.setSizePolicy(sizePolicy)
        self.s_3_up.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/arrows/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/up/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.s_3_up.setIcon(icon)
        self.s_3_up.setIconSize(QtCore.QSize(50, 50))
        self.s_3_up.setObjectName("s_3_up")
        self.horizontalLayout.addWidget(self.s_3_up)
        self.s_2_up = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s_2_up.sizePolicy().hasHeightForWidth())
        self.s_2_up.setSizePolicy(sizePolicy)
        self.s_2_up.setText("")
        self.s_2_up.setIcon(icon)
        self.s_2_up.setIconSize(QtCore.QSize(50, 50))
        self.s_2_up.setObjectName("s_2_up")
        self.horizontalLayout.addWidget(self.s_2_up)
        self.s_1_up = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s_1_up.sizePolicy().hasHeightForWidth())
        self.s_1_up.setSizePolicy(sizePolicy)
        self.s_1_up.setText("")
        self.s_1_up.setIcon(icon)
        self.s_1_up.setIconSize(QtCore.QSize(50, 50))
        self.s_1_up.setObjectName("s_1_up")
        self.horizontalLayout.addWidget(self.s_1_up)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.s3 = QtWidgets.QLCDNumber(self.widget)
        self.s3.setDigitCount(1)
        self.s3.setObjectName("s3")
        self.horizontalLayout_3.addWidget(self.s3)
        self.s2 = QtWidgets.QLCDNumber(self.widget)
        self.s2.setDigitCount(1)
        self.s2.setObjectName("s2")
        self.horizontalLayout_3.addWidget(self.s2)
        self.s1 = QtWidgets.QLCDNumber(self.widget)
        self.s1.setDigitCount(1)
        self.s1.setObjectName("s1")
        self.horizontalLayout_3.addWidget(self.s1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.s_3_down = QtWidgets.QPushButton(self.widget)
        self.s_3_down.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/arrows/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.s_3_down.setIcon(icon1)
        self.s_3_down.setIconSize(QtCore.QSize(50, 50))
        self.s_3_down.setObjectName("s_3_down")
        self.horizontalLayout_2.addWidget(self.s_3_down)
        self.s_2_down = QtWidgets.QPushButton(self.widget)
        self.s_2_down.setText("")
        self.s_2_down.setIcon(icon1)
        self.s_2_down.setIconSize(QtCore.QSize(50, 50))
        self.s_2_down.setObjectName("s_2_down")
        self.horizontalLayout_2.addWidget(self.s_2_down)
        self.s_1_down = QtWidgets.QPushButton(self.widget)
        self.s_1_down.setText("")
        self.s_1_down.setIcon(icon1)
        self.s_1_down.setIconSize(QtCore.QSize(50, 50))
        self.s_1_down.setObjectName("s_1_down")
        self.horizontalLayout_2.addWidget(self.s_1_down)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.dry = QtWidgets.QLabel(self.widget)
        self.dry.setObjectName("dry")
        self.horizontalLayout_5.addWidget(self.dry)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.d_2_up = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.d_2_up.sizePolicy().hasHeightForWidth())
        self.d_2_up.setSizePolicy(sizePolicy)
        self.d_2_up.setText("")
        self.d_2_up.setIcon(icon)
        self.d_2_up.setIconSize(QtCore.QSize(50, 50))
        self.d_2_up.setObjectName("d_2_up")
        self.horizontalLayout_6.addWidget(self.d_2_up)
        self.d_1_up = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.d_1_up.sizePolicy().hasHeightForWidth())
        self.d_1_up.setSizePolicy(sizePolicy)
        self.d_1_up.setText("")
        self.d_1_up.setIcon(icon)
        self.d_1_up.setIconSize(QtCore.QSize(50, 50))
        self.d_1_up.setObjectName("d_1_up")
        self.horizontalLayout_6.addWidget(self.d_1_up)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.d2 = QtWidgets.QLCDNumber(self.widget)
        self.d2.setDigitCount(1)
        self.d2.setObjectName("d2")
        self.horizontalLayout_7.addWidget(self.d2)
        self.d1 = QtWidgets.QLCDNumber(self.widget)
        self.d1.setDigitCount(1)
        self.d1.setObjectName("d1")
        self.horizontalLayout_7.addWidget(self.d1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.d_2_down = QtWidgets.QPushButton(self.widget)
        self.d_2_down.setText("")
        self.d_2_down.setIcon(icon1)
        self.d_2_down.setIconSize(QtCore.QSize(50, 50))
        self.d_2_down.setObjectName("d_2_down")
        self.horizontalLayout_8.addWidget(self.d_2_down)
        self.d_1_down = QtWidgets.QPushButton(self.widget)
        self.d_1_down.setText("")
        self.d_1_down.setIcon(icon1)
        self.d_1_down.setIconSize(QtCore.QSize(50, 50))
        self.d_1_down.setObjectName("d_1_down")
        self.horizontalLayout_8.addWidget(self.d_1_down)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.number = QtWidgets.QLabel(self.widget)
        self.number.setObjectName("number")
        self.horizontalLayout_9.addWidget(self.number)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.n_2_up = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n_2_up.sizePolicy().hasHeightForWidth())
        self.n_2_up.setSizePolicy(sizePolicy)
        self.n_2_up.setText("")
        self.n_2_up.setIcon(icon)
        self.n_2_up.setIconSize(QtCore.QSize(50, 50))
        self.n_2_up.setObjectName("n_2_up")
        self.horizontalLayout_10.addWidget(self.n_2_up)
        self.n_1_up = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n_1_up.sizePolicy().hasHeightForWidth())
        self.n_1_up.setSizePolicy(sizePolicy)
        self.n_1_up.setText("")
        self.n_1_up.setIcon(icon)
        self.n_1_up.setIconSize(QtCore.QSize(50, 50))
        self.n_1_up.setObjectName("n_1_up")
        self.horizontalLayout_10.addWidget(self.n_1_up)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.n2 = QtWidgets.QLCDNumber(self.widget)
        self.n2.setDigitCount(1)
        self.n2.setObjectName("n2")
        self.horizontalLayout_11.addWidget(self.n2)
        self.n1 = QtWidgets.QLCDNumber(self.widget)
        self.n1.setDigitCount(1)
        self.n1.setObjectName("n1")
        self.horizontalLayout_11.addWidget(self.n1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.n_2_down = QtWidgets.QPushButton(self.widget)
        self.n_2_down.setText("")
        self.n_2_down.setIcon(icon1)
        self.n_2_down.setIconSize(QtCore.QSize(50, 50))
        self.n_2_down.setObjectName("n_2_down")
        self.horizontalLayout_12.addWidget(self.n_2_down)
        self.n_1_down = QtWidgets.QPushButton(self.widget)
        self.n_1_down.setText("")
        self.n_1_down.setIcon(icon1)
        self.n_1_down.setIconSize(QtCore.QSize(50, 50))
        self.n_1_down.setObjectName("n_1_down")
        self.horizontalLayout_12.addWidget(self.n_1_down)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_9)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(40, 320, 201, 61))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_14.addWidget(self.label_2)
        self.current_cycle = QtWidgets.QLCDNumber(self.widget1)
        self.current_cycle.setDigitCount(2)
        self.current_cycle.setObjectName("current_cycle")
        self.horizontalLayout_14.addWidget(self.current_cycle)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(420, 260, 181, 141))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.start = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start.sizePolicy().hasHeightForWidth())
        self.start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.start.setFont(font)
        self.start.setStyleSheet("background-color: rgb(172, 255, 127);")
        self.start.setObjectName("start")
        self.verticalLayout_4.addWidget(self.start)
        self.stop = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop.sizePolicy().hasHeightForWidth())
        self.stop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.stop.setFont(font)
        self.stop.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.stop.setObjectName("stop")
        self.verticalLayout_4.addWidget(self.stop)
        self.spray.raise_()
        self.label_2.raise_()
        self.label_2.raise_()
        self.current_cycle.raise_()
        self.start.raise_()
        self.stop.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.spray.setText(_translate("MainWindow", "Spray cycle :\n"
" in seconds"))
        self.dry.setText(_translate("MainWindow", "Dry cycle :\n"
" in seconds"))
        self.number.setText(_translate("MainWindow", "No. of cycle:"))
        self.label_2.setText(_translate("MainWindow", "Currently running cycle"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.stop.setText(_translate("MainWindow", "Stop"))

import arr_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

